//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_question()
        {
            this.t_quiz = new HashSet<t_quiz>();
        }
    
        public int QuestionId { get; set; }
        public string Question { get; set; }
        public int CreatorId { get; set; }
        public string Answer { get; set; }
    
        public virtual t_options t_options { get; set; }
        public virtual t_user t_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_quiz> t_quiz { get; set; }
    }
}
